language picker (not complete)
Ivy-Apps/ivy-wallet pull request #1839
Opened 2023-02-02 19:13 UTC by shashank-0-0

## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `develop` branch.
- [x] I understand the **[Ivy Developer Guidelines](../docs/Developer-Guidelines.md)**.
- [x] I've read the **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md)**.
- [x] The code builds and is tested on an actual Android device.
- [x] I confirm that I've run the code locally and everything works as expected.
- [ ] I confirm that I've run Ivy Wallet's UI tests (`androidTest`) and all tests are passing
  successfully.

_Put an `x` in the boxes that apply._

## Pull Request Type
Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, new lines, etc.)
- [ ] Refactoring (no functional changes, renaming)
- [ ] Small improvement (fix typo, UI fine-tune, change color or something small)
- [ ] Gradle Build related changes
- [ ] Dependencies update (updating libraries)
- [ ] Documentation (clarifying comments, KDoc)
- [ ] Tests (Unit, Integration, UI tests)
- [ ] Other (please describe):

_Put an `x` in the boxes that apply._

## Does this PR closes any GitHub Issues?
Check **[Ivy Wallet Issues](https://github.com/Ivy-Apps/ivy-wallet/issues)**.
- Closes #1740  (type issue number here)

## What's changed?
Describe with a few bullets **what's new:**
- Added an in app language picker in settings screen.
- Used per app language preferences api to change the locale
- Not complete yet some more changes need to be done ,this pr is for review purpose

2023-02-02 19:47 UTC, ILIYANGERMANOV requested changes

2023-02-02 19:47 UTC, ILIYANGERMANOV commented on buildSrc/src/main/java/com/ivy/buildsrc/dependencies.kt
> +fun DependencyHandler.AppCompat_1(api:Boolean) {
Just update our AppCompat, don't duplicate it

2023-02-02 19:47 UTC, ILIYANGERMANOV commented on settings/build.gradle.kts
> +    AppCompat_1(true)
Save, remove this

2023-02-02 19:47 UTC, ILIYANGERMANOV commented on settings/src/main/java/com/ivy/settings/SettingsScreen.kt
> +     val list by lazy{
This must be added to `SettingsState` and provided from the `SettingsViewModel`

2023-02-02 19:47 UTC, ILIYANGERMANOV commented on app/src/main/AndroidManifest.xml
> +<!--        make sures locale changes is persisted -->
Nice comment! Just a minor typo: should be "are persisted"

2023-02-03 18:37 UTC, shashank-0-0 commented
I have made made the requested changes and added a state for the current chosen language. 
If there are any more changes needed would be happy to rework.

2023-02-03 19:19 UTC, ILIYANGERMANOV requested changes
Hi, thank you for applying my suggestions! Overall, it looks great 👍 Just a few more details to resolve and I'll be ready to merge it

2023-02-03 19:19 UTC, ILIYANGERMANOV commented on settings/build.gradle.kts
> +    AppCompat(true)
`AppCompat(api = false)` because it shouldn't be an API gradle

2023-02-03 19:19 UTC, ILIYANGERMANOV commented on settings/src/main/java/com/ivy/settings/SettingsScreen.kt
> +        state.supportedLanguages,
1. add names to arguments
2. put `onLanguageChange` as last

2023-02-03 19:19 UTC, ILIYANGERMANOV commented on settings/src/main/java/com/ivy/settings/SettingsScreen.kt
> +fun setVisibility(currentLanguageCode: String,language: Language) : Visibility {
No need for this function. 

Do it directly via 
```
if(..) Focused else Medium
```

2023-02-03 19:19 UTC, ILIYANGERMANOV commented on settings/src/main/java/com/ivy/settings/SettingsState.kt
> +    val supportedLanguages:List<Language>,
Please format the code, when committing check "Reformar code".

2023-02-03 19:19 UTC, ILIYANGERMANOV commented on settings/src/main/java/com/ivy/settings/data/Ivy_languages.kt
> +enum class Language(val languageCode: String) {
We use these style for enum:
```
Enlish("en"),
Spanish("es"),
...
```

2023-02-04 07:23 UTC, shashank-0-0 commented
Done with the minor changes..

2023-02-04 10:50 UTC, ILIYANGERMANOV approved these changes
Thank you for making all changes! Your contribution is much appreciated and will help our internationalization efforts greatly

2023-02-04 10:59 UTC, merged

2023-02-04 11:38 UTC, ILIYANGERMANOV commented
@shashank-0-0 nice! The language selection works very well