Income and expenses in alphabetic order
Ivy-Apps/ivy-wallet pull request #3192
Opened 2024-05-12 00:07 UTC by luispacheco-dev

## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `main` branch.
- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [x] I've read and understand the [Developer Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Guidelines.md).
- [x] I confirm that I've run the code locally and everything works as expected.
- [ ] 🎬 I've attached a **screen recoding** of the changes. 

![Screenshot_20240511_170600](https://github.com/Ivy-Apps/ivy-wallet/assets/132418600/1020c463-fce9-48dd-89d7-82245f2e41b8)

2024-05-12 13:28 UTC, ILIYANGERMANOV requested changes

2024-05-12 13:28 UTC, ILIYANGERMANOV commented on screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionViewModel.kt
> +                categories.value = categoryRepository.findAll().sortedBy { it.name.value }.toImmutableList()
This shouldn't be the default behavior. Most users prefer to see the categories in the order that they've put them in the Categories screen. Make this feature a Setting using `Features` and IvyFeatures and by default it must be off

2024-05-12 13:28 UTC, ILIYANGERMANOV commented on screen/edit-transaction/src/main/java/com/ivy/transaction/EditTransactionViewModel.kt
> +                categories.value = categoryRepository.findAll().sortedBy { it.name.value }.toImmutableList()
This code is duplicated 3 times, extract it as a function

2024-05-15 03:57 UTC, luispacheco-dev commented
I'm going to close this PR because I sent other with the changes.

2024-05-15 03:57 UTC, closed without merging