disabled firebase crashlytics
Ivy-Apps/ivy-wallet pull request #3310
Opened 2024-07-08 21:48 UTC by suyash01

## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `main` branch.
- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [x] I've read and understand the [Developer Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Guidelines.md).
- [ ] I confirm that I've run the code locally and everything works as expected.
- [ ] 🎬 I've attached a **screen recoding** of the changes.
- [x] My PR includes only the necessary changes to fix the issue (i.e., no unnecessary files or lines of code are changed).

> Tip: drag & drop the video to the PR description.

## What's changed?

Describe with a few bullets **what's new:**
- a
- b
- c

> 💡 Tip: Please, attach screenshots and screen recordings. It helps a lot!

## Risk Factors

**What may go wrong if we merge your PR?**

- a
- b

**In what cases your code won't work?**

- a
- b

## Does this PR closes any GitHub Issues?

Check **[Ivy Wallet Issues](https://github.com/Ivy-Apps/ivy-wallet/issues)**.

- Closes #ISSUE_NUMBER

> Replace `ISSUE_NUMBER` with the number of the GitHub issue that this PR is fixing. If you've done that correctly, you'll see the issue title linked when previewing your PR description.

> **!Note:** Do **not** link the PR number. Link the number/id of the GitHub Issue from [issues](https://github.com/Ivy-Apps/ivy-wallet/issues).

## Troubleshooting CI failures ❌

GitHub Actions failing? Read our [CI Troubleshooting guide](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/CI-Troubleshooting.md).

2024-07-08 21:50 UTC, suyash01 commented
@ILIYANGERMANOV I have made some changes but from the logs it is not entirely clear if the crash logs are being pushed to firebase or not. If you get some time, could you test this with firebase? I have made the transaction button to throw exception to emulate crash.

2024-07-08 21:57 UTC, ILIYANGERMANOV requested changes
To effectively remove Firebase you need to somehow declare it as "release" only dependencies. If the library is in the dependencies, we gain no benefits.

The problem that we need to solve is:
- get all Firebase and Google dependencies removed from the classpath on "debug" builds
- keep Firebase only for "release" builds

2024-07-08 21:57 UTC, ILIYANGERMANOV commented on app/build.gradle.kts
> +                mappingFileUploadEnabled = false
This removes the deobfuscation mapping. I.e., still uploads crashes but as gibberish.

2024-07-08 21:58 UTC, ILIYANGERMANOV commented on app/src/main/java/com/ivy/wallet/IvyAndroidApp.kt
> +            Firebase.crashlytics.setCrashlyticsCollectionEnabled(true)
This should probably work, especially if you've disable Firebase auto-init

2024-07-09 16:07 UTC, suyash01 commented
@ILIYANGERMANOV I am spending way too much time on this and my lack of firebase knowledge is not helping. If you have any idea let know otherwise i will close this PR and unassign myself from the ticket.

2024-07-09 16:38 UTC, ILIYANGERMANOV commented
> @ILIYANGERMANOV I am spending way too much time on this and my lack of firebase knowledge is not helping. If you have any idea let know otherwise i will close this PR and unassign myself from the ticket.

Yeah, it's a tricky one. Feel free to unassign^

2024-07-09 21:34 UTC, closed without merging