feat: Add "Total Remaining Budget" display
Ivy-Apps/ivy-wallet pull request #3368
Opened 2024-07-25 13:33 UTC by akashs056

## Pull request (PR) checklist
Please check if your pull request fulfills the following requirements:

- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [x] I've read and understand the [Developer Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Guidelines.md).
- [x] I confirm that I've run the code locally and everything works as expected.
- [x] My PR includes only the necessary changes to fix the issue (i.e., no unnecessary files or lines of code are changed).
- [x] 🎬 I've attached a **screen recording** of using the new code to the next paragraph (if applicable).

## Screen recording of interacting with your changes:

https://github.com/user-attachments/assets/b2ad6d2b-a159-4f51-ba60-80ce8fa4c500

## What's changed?
 - Added display for "Total Remaining Budget" beneath budget information. 
 - Calculated remaining budget for categorized and multi-categorized budgets.
 - Included multi-language support for the "Total Remaining Budget" text. 
 - Enhanced user experience by providing a clear overview of remaining budget without manual summarization.

## Does this PR close any GitHub issues? (do not delete)
- Closes #3365

2024-07-25 13:56 UTC, ILIYANGERMANOV requested changes
Overall looks good, a few changes:
- use `String?` for the UI state of the new text 
- do the calculation and formatting in the VM

This is needed for performance and architecture reasons.

2024-07-25 13:56 UTC, ILIYANGERMANOV commented on screen/budgets/src/main/java/com/ivy/budgets/BudgetViewModel.kt
> +            this@BudgetViewModel.totalRemainingBudget.doubleValue = calculateTotalRemainingBudget(
no need for `this@`, if there's a clash of names rename to `totalRemainingBudgetState`

2024-07-25 13:56 UTC, ILIYANGERMANOV commented on screen/budgets/src/main/java/com/ivy/budgets/BudgetViewModel.kt
> +            .filter { !it.budget.categoryIdsSerialized.isNullOrBlank() }
use `isNotNullOrBlank()` and also add a comment that you're filtering to only Category budgets

2024-07-25 13:56 UTC, ILIYANGERMANOV commented on screen/budgets/src/main/java/com/ivy/budgets/BudgetScreen.kt
> +    val budgetExceeded = totalRemainingBudget < 0
Move `budgetExceeded` as close as possible to its usages

2024-07-25 13:56 UTC, ILIYANGERMANOV commented on screen/budgets/src/main/java/com/ivy/budgets/BudgetScreen.kt
> +                val totalRemainingText = when {
This transformation should be done in the VM. Change the UI state to be `: String?` and do this calculation and formating in the VM

2024-07-25 13:56 UTC, ILIYANGERMANOV commented on screen/budgets/src/main/java/com/ivy/budgets/BudgetScreen.kt
> +                if (categoryBudgetText.isNotEmpty()) {
Is this `if` correct? I guess we need to check `totalRemaingText` not being null

2024-07-25 13:57 UTC, ILIYANGERMANOV commented
Ping me for re-review when you've applied the changes

2024-07-26 08:50 UTC, akashs056 commented
@ILIYANGERMANOV applied the changes. please re-review it

2024-07-26 09:12 UTC, ILIYANGERMANOV requested changes
Remove unnecessary state, fix Detekt and we can merge

2024-07-26 09:12 UTC, ILIYANGERMANOV commented on screen/budgets/src/main/java/com/ivy/budgets/BudgetViewModel.kt
> +    private val totalRemainingBudgetText = mutableStateOf<String?>("")
We don't need this state - just transform the double state inside `getTotalRemainingBudgetText()`

2024-07-26 09:12 UTC, ILIYANGERMANOV commented on screen/budgets/src/main/java/com/ivy/budgets/BudgetViewModel.kt
> +        totalRemainingBudgetText.value = when {
Remove the unnecessary text state and just put `return` here

2024-07-26 09:49 UTC, akashs056 commented
its ready to merge

2024-07-26 09:51 UTC, ILIYANGERMANOV approved these changes

2024-07-26 09:51 UTC, merged