Fix issue 3364
Ivy-Apps/ivy-wallet pull request #3431
Opened 2024-08-26 16:47 UTC by rodrigomatosc

## Pull request (PR) checklist

Please check if your pull request fulfills the following requirements:

- [ ] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [ ] I've read and understand the [Developer Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Guidelines.md).
- [ ] I confirm that I've run the code locally and everything works as expected.
- [ ] My PR includes only the necessary changes to fix the issue (i.e., no unnecessary files or lines of code are changed).
- [ ] 🎬 I've attached a **screen recording** of using the new code to the next paragraph (if applicable).

## Screen recording of your changes (if applicable):

## What's changed?

Describe with a few bullets **what's new:**
- I've fixed...

Before|After
---|---
{media}|{media}
{media}|{media}

## Risk factors

**What may go wrong if we merge your PR?**
- ...
- ...

**In what cases won't your code work?**
- ...
- ...

## Does this PR close any GitHub issues? (do not delete)

- Closes #{ISSUE_NUMBER}

## Troubleshooting GitHub Actions (CI) failures ❌
Pull request checks failing? Read our [CI Troubleshooting guide](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/CI-Troubleshooting.md).

2024-08-26 18:09 UTC, ILIYANGERMANOV reviewed
LGTM! Left some comments and we ca  merge after they're fixed

2024-08-26 18:09 UTC, ILIYANGERMANOV commented on shared/domain/src/main/java/com/ivy/domain/features/IvyFeatures.kt
> +        description = "Activates a more streamlined and space-efficient interface for the \"Categories\" tab"
"Categories" screen,  not tab

2024-08-26 18:09 UTC, ILIYANGERMANOV commented on screen/categories/src/main/java/com/ivy/categories/CategoriesScreen.kt
> +private fun PreviewCategoriesCompactModeEnabled(theme: Theme = Theme.LIGHT) {
You need to record Paparazzi screneshots for this module. See the CI guide at the bottom of your PR description

2024-08-26 18:13 UTC, ILIYANGERMANOV requested changes
The UI on the Categories screen should display "+" or "-" before the amount depending on whether the net balance for the category is positive. 

when {
  x > 0 -> "+"
  0 -> ""
  x < 0 -> "-"
}

2024-08-26 18:13 UTC, ILIYANGERMANOV commented
> The UI on the Categories screen should display "+" or "-" before the amount depending on whether the net balance for the category is positive.
> 
> when { x > 0 -> "+" 0 -> "" x < 0 -> "-" }

This might not be caused by your PR but we should fix it 🙏

2024-08-27 12:43 UTC, rodrigomatosc commented
> The UI on the Categories screen should display "+" or "-" before the amount depending on whether the net balance for the category is positive.
> 
> when { x > 0 -> "+" 0 -> "" x < 0 -> "-" }

The current rule implementeg in the default card header is : 

<img width="513" alt="image" src="https://github.com/user-attachments/assets/4afe1c76-9ce8-4c18-adef-f936cf623120">

Would you like me to modify the implementation to match the one you indicated ?

2024-08-27 12:45 UTC, ILIYANGERMANOV commented
> > The UI on the Categories screen should display "+" or "-" before the amount depending on whether the net balance for the category is positive.
> > when { x > 0 -> "+" 0 -> "" x < 0 -> "-" }
> 
> The current rule implementeg in the default card header is :
> 
> <img alt="image" width="513" src="https://private-user-images.githubusercontent.com/22649983/361807380-4afe1c76-9ce8-4c18-adef-f936cf623120.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjI5NzksIm5iZiI6MTcyNDc2MjY3OSwicGF0aCI6Ii8yMjY0OTk4My8zNjE4MDczODAtNGFmZTFjNzYtOWNlOC00YzE4LWFkZWYtZjkzNmNmNjIzMTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEyNDQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkYmRkNmI3ZGEwMGMwNjExNGNkOGY3YmIxNjgzODdiYjlmMTJiNWFhODBhNzc5NDZmMzJjMTNjNjUxYzBiM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IhNhi0EWNt-TouChL8whhvuRgXIq5JpM9quYq-IYC08">
> Would you like me to modify the implementation to match the one you indicated ?

Yup, with the new design not showing +/- makes it confusing. I read between the lines but end goal is the Category screen to makes sense for the user

2024-08-27 13:52 UTC, ILIYANGERMANOV commented on screen/categories/src/test/snapshots/images/com.ivy.categories_CategoriesScreenPaparazziTest_snapshot Categories compact Screen[Dark].png
Just remove the space between "+ 2,150" and we're good to merge 👍 Tag me for re-review and will merge it

2024-08-27 16:37 UTC, ILIYANGERMANOV approved these changes

2024-08-27 16:37 UTC, merged