BottomBar added on Exchange Rates Screen
Ivy-Apps/ivy-wallet pull request #3508
Opened 2024-09-14 11:47 UTC by shamim-emon

## Pull request (PR) checklist

Please check if your pull request fulfills the following requirements:

- [ ] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [ ] I've read and understand the [Developer Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Guidelines.md).
- [ ] I confirm that I've run the code locally and everything works as expected.
- [ ] My PR includes only the necessary changes to fix the issue (i.e., no unnecessary files or lines of code are changed).
- [ ] 🎬 I've attached a **screen recording** of using the new code to the next paragraph (if applicable).

## What's changed?
- I've added Bottom bar (having navigation back button) on `Exchange Rates` screen

Before(Left) | After(Right)

![Dark](https://github.com/user-attachments/assets/635f6ef7-3022-4c5c-8684-931c69a5cadc)
![light](https://github.com/user-attachments/assets/41a55d12-ca7f-44ec-a432-3bf93dae4f6c)

**What may go wrong if we merge your PR?**
- N/A

**In what cases won't your code work?**
- N/A

## Does this PR close any GitHub issues? (do not delete)

- Closes #3504 

## Troubleshooting GitHub Actions (CI) failures ❌
Pull request checks failing? Read our [CI Troubleshooting guide](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/CI-Troubleshooting.md).

2024-09-14 20:15 UTC, ILIYANGERMANOV requested changes

2024-09-14 20:15 UTC, ILIYANGERMANOV commented on shared/ui/core/src/main/res/values-bg/strings.xml
> +    <string name="add_manual_exchange_rate">Add  rate</string>
Remove unnecessary space "  " from all strings

2024-09-15 01:04 UTC, shamim-emon commented on shared/ui/core/src/main/res/values-bg/strings.xml
> +    <string name="add_manual_exchange_rate">Add  rate</string>
Done

2024-09-15 12:01 UTC, ILIYANGERMANOV approved these changes

2024-09-15 12:01 UTC, merged