Fix #3432 Recurring expenses spawn at UTC timing instead of local time
Ivy-Apps/ivy-wallet pull request #3570
Opened 2024-09-29 12:25 UTC by Mushfiq1060

## Pull request (PR) checklist

Please check if your pull request fulfills the following requirements:

- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [x] I've read and understand the [Developer Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Guidelines.md).
- [x] I confirm that I've run the code locally and everything works as expected.
- [x] My PR includes only the necessary changes to fix the issue (i.e., no unnecessary files or lines of code are changed).
- [ ] 🎬 I've attached a **screen recording** of using the new code to the next paragraph (if applicable).

## Screen recording of your changes (if applicable):
No

## What's changed?
Assume that on September 29, 2024, we create a recurring expense named **`MyRecurrentExpense`**. Consequently, an entry for **`MyRecurrentExpense`** appears in the **`upcoming section`** of the home screen for September 29. Previously, this entry was moved to the **`overdue section`** at 12:00 AM UTC rather than 12:00 AM local time. Now, the entry is moved to the **`overdue section`** at 12:00 AM local time.

**N.B:** Expenses from September 29 will move to the **`overdue section`** on September 30 at 12:00 AM local time.

## Risk factors

**What may go wrong if we merge your PR?**
No

**In what cases won't your code work?**
No

## Does this PR close any GitHub issues? (do not delete)

- Closes N/A

2024-09-29 12:51 UTC, ILIYANGERMANOV requested changes

2024-09-29 12:51 UTC, ILIYANGERMANOV commented on temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/RecurringRuleModal.kt
> +        mutableStateOf(modal?.initialStartDate ?: timeNowLocal())
Use `LocalTimeProvider` composition local to get the current time instead

2024-09-29 12:51 UTC, ILIYANGERMANOV commented on temp/legacy-code/src/main/java/com/ivy/legacy/domain/action/viewmodel/home/DueTrnsInfoAct.kt
> +                Instant.now().toLocalDate()
Use `TimeProvider`

2024-09-29 12:51 UTC, ILIYANGERMANOV commented
@Mushfiq1060 add screen recording to prove that it worms

2024-09-29 12:52 UTC, Mushfiq1060 commented
ok

2024-09-29 13:13 UTC, Mushfiq1060 commented
@ILIYANGERMANOV screen recording

https://github.com/user-attachments/assets/dc92f79d-3ec5-4b9b-8793-525c15ebbcc5

2024-09-29 13:15 UTC, ILIYANGERMANOV commented on temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/RecurringRuleModal.kt
> +    val localTimeProvider = LocalTimeProvider.current
just call it timeProvider

2024-09-29 13:22 UTC, ILIYANGERMANOV approved these changes

2024-09-30 03:49 UTC, shamim-emon approved these changes

2024-09-30 08:24 UTC, merged